name: PHP Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Build Docker Image
      - name: Build Docker Image
        run: docker-compose build

      # 4. Run Docker Containers
      - name: Start Docker Containers
        run: docker-compose up -d

      # 5. Run Tests (Optional)
      # If you have PHP unit tests, you can run them here. Otherwise, you can skip this step.
      # - name: Run Tests
      #   run: phpunit

      # 6. Stop and Clean up Docker Containers
      - name: Stop Docker Containers
        run: docker-compose down
